AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Momentum Ink Server

Parameters:
  MasterPassword:
    Description: Database master password.
    NoEcho: true
    Type: String

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MomentumInk
      GroupDescription: Security group for MomentumInk related infrastructure
      VpcId: vpc-0b79df987bdd82ec6
  SecurityGroupSelfReference:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Intra-group traffic
      FromPort: -1
      GroupId: !Ref SecurityGroup
      IpProtocol: '-1'
      SourceSecurityGroupId: !Ref SecurityGroup
      ToPort: -1

  MinkServer:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Events:
        Api:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Handler: dist/handler.handle
      Runtime: nodejs8.10
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          - subnet-0cfe5e30ebe1c45ce
          - subnet-0fd2ccc80895bc7e6
          - subnet-0d7efc2ffac0285e3

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: MomemntumInk
      DBSubnetGroupName: production-private
      DeletionProtection: true
      Engine: default.aurora5.6
      EngineMode: Serverless
      MasterUsername: master
      MasterUserPassword: !Ref MasterPassword
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      StorageEncrypted: true
      Tags:
        - Key: Application
          Value: Job Board
        - Key: Client
          Value: Momentum Ink
        - Key: Environment
          Value: Production
      VpcSecurityGroupIds:
        - !Ref SecurityGroup

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
